
adjective1 = input("Enter an adjective: ")
name1 = input("Enter a first name: ")
adjective2 = input("Enter another adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
animal = input("Enter an animal: ")
verb2 = input("Enter a verb with ing: ")
adverb = input("Enter an adverb: ")
adjective3 = input("Enter an adjective: ")
name2 = input("Enter a name: ")
adjective4 = input("Enter an adjective: ")
noun2 = input("Enter a noun: ")
verb3 = input("Enter a Verb with ing:")
noun3 = input("Enter a plural noun: ")
verb4 = input("Enter a Verb with ing: ")

print("They say my school is haunted,my " + adjective1 + " " + "friend" + " " + name1 + " " + "says she saw a" + " " + adjective2 + " " + noun1 + " " + "floating at the end of the hall near the cafeteria.")
print("Some say if you " + verb1 + "down that hallway at night, you'll hear a " + animal + " " + verb2 + " " + adverb)
print("My " + adjective3 + "friend " + name2 + "saw a " + adjective4 + " " + noun2 + " " + verb3 + " " + "under one of the tables once.")
print("I hope I never see any " + noun3 + " " + verb4 + " " +"eating lunch there is scary enough! ")
